package tablas;
// Generated 28 dic 2021 17:07:02 by Hibernate Tools 5.5.7.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proyecto generated by hbm2java
 */
public class Proyecto implements java.io.Serializable {

	private String nombre;
	private int duracion;
	private Date fechIn;
	private Date fechFin;
	private Set tareas = new HashSet(0);
	private Set empleados = new HashSet(0);

	public Proyecto() {
	}

	public Proyecto(String nombre, int duracion, Date fechIn) {
		this.nombre = nombre;
		this.duracion = duracion;
		this.fechIn = fechIn;
	}

	public Proyecto(String nombre, int duracion, Date fechIn, Date fechFin, Set tareas, Set empleados) {
		this.nombre = nombre;
		this.duracion = duracion;
		this.fechIn = fechIn;
		this.fechFin = fechFin;
		this.tareas = tareas;
		this.empleados = empleados;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getDuracion() {
		return this.duracion;
	}

	public void setDuracion(int duracion) {
		this.duracion = duracion;
	}

	public Date getFechIn() {
		return this.fechIn;
	}

	public void setFechIn(Date fechIn) {
		this.fechIn = fechIn;
	}

	public Date getFechFin() {
		return this.fechFin;
	}

	public void setFechFin(Date fechFin) {
		this.fechFin = fechFin;
	}

	public Set getTareas() {
		return this.tareas;
	}

	public void setTareas(Set tareas) {
		this.tareas = tareas;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

}
