package tablas;
// Generated 8 ene 2022 17:58:19 by Hibernate Tools 5.5.7.Final

/**
 * TareaId generated by hbm2java
 */
public class TareaId implements java.io.Serializable {

	private String nombreProyecto;
	private String nombre;

	public TareaId() {
	}

	public TareaId(String nombreProyecto, String nombre) {
		this.nombreProyecto = nombreProyecto;
		this.nombre = nombre;
	}

	public String getNombreProyecto() {
		return this.nombreProyecto;
	}

	public void setNombreProyecto(String nombreProyecto) {
		this.nombreProyecto = nombreProyecto;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TareaId))
			return false;
		TareaId castOther = (TareaId) other;

		return ((this.getNombreProyecto() == castOther.getNombreProyecto())
				|| (this.getNombreProyecto() != null && castOther.getNombreProyecto() != null
						&& this.getNombreProyecto().equals(castOther.getNombreProyecto())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombreProyecto() == null ? 0 : this.getNombreProyecto().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		return result;
	}

}
